/**
 * Workflow Detail Page
 * 
 * Shows workflow definition, steps, validation status, and execution controls
 */

import { Suspense } from 'react';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { requireAuth, requireProfile } from '@/lib/auth/session';
import { getWorkflowDetailsAction } from '../actions';
import { AppShell, PageContainer, PageHeader, ErrorState, LoadingState } from '@/components/layout';
import { WorkflowStatusActions } from './WorkflowStatusActions';
import { WorkflowExecutionPanel } from './WorkflowExecutionPanel';

interface WorkflowStep {
  id: string;
  step_name?: string;
  name?: string;
  action_type?: string;
  step_type?: string;
  requires_approval?: boolean;
  is_mandatory?: boolean;
}

async function WorkflowDetailContent({ workflowId }: { workflowId: string}) {
  const result = await getWorkflowDetailsAction(workflowId);

  if (!result.success) {
    if (result.error?.includes('not found')) {
      notFound();
    }
    return <ErrorState message={result.error || 'Failed to load workflow'} />;
  }

  const workflow = result.data!;
  const steps = workflow.steps || [];

  return (
    <div>
      <PageHeader
        title={workflow.name}
        description={workflow.description}
      />

      {/* Workflow Metadata */}
      <div className="bg-white shadow sm:rounded-lg mb-6">
        <div className="px-4 py-5 sm:p-6">
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
            <div>
              <dt className="text-sm font-medium text-gray-500">Status</dt>
              <dd className="mt-1 text-sm text-gray-900">
                <StatusBadge status={workflow.status} />
              </dd>
            </div>
            <div>
              <dt className="text-sm font-medium text-gray-500">Version</dt>
              <dd className="mt-1 text-sm text-gray-900">{workflow.version}</dd>
            </div>
            <div>
              <dt className="text-sm font-medium text-gray-500">Steps</dt>
              <dd className="mt-1 text-sm text-gray-900">{steps.length}</dd>
            </div>
          </div>

          {workflow.validation_errors && (
            <div className="mt-4 p-4 bg-red-50 border border-red-200 rounded-md">
              <h4 className="text-sm font-medium text-red-800 mb-2">
                Validation Errors
              </h4>
              <ul className="text-sm text-red-700 list-disc list-inside space-y-1">
                {workflow.validation_errors.map((error: string, idx: number) => (
                  <li key={idx}>{error}</li>
                ))}
              </ul>
            </div>
          )}

          {workflow.ai_generated && workflow.ai_generation_metadata && (
            <div className="mt-4 p-4 bg-blue-50 border border-blue-200 rounded-md">
              <div className="flex items-start">
                <div className="flex-shrink-0">
                  <svg
                    className="h-5 w-5 text-blue-400"
                    fill="currentColor"
                    viewBox="0 0 20 20"
                  >
                    <path
                      fillRule="evenodd"
                      d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z"
                      clipRule="evenodd"
                    />
                  </svg>
                </div>
                <div className="ml-3">
                  <h4 className="text-sm font-medium text-blue-800">
                    AI-Generated Workflow
                  </h4>
                  <p className="mt-1 text-sm text-blue-700">
                    {typeof workflow.ai_generation_metadata === 'object' &&
                    'model' in workflow.ai_generation_metadata
                      ? `Generated by ${workflow.ai_generation_metadata.model}`
                      : 'Generated by AI'}
                  </p>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Status Actions */}
      <WorkflowStatusActions
        workflowId={workflow.id}
        status={workflow.status}
        reviewed={workflow.reviewed}
      />

      {/* Workflow Steps */}
      <div className="bg-white shadow sm:rounded-lg mb-6">
        <div className="px-4 py-5 sm:p-6">
          <h3 className="text-lg font-medium text-gray-900 mb-4">
            Workflow Steps
          </h3>
          {steps.length === 0 ? (
            <p className="text-sm text-gray-500">No steps defined</p>
          ) : (
            <div className="space-y-4">
              {steps.map((step: WorkflowStep, index: number) => (
                <div
                  key={step.id}
                  className="border border-gray-200 rounded-lg p-4"
                >
                  <div className="flex items-start justify-between">
                    <div className="flex items-start gap-3">
                      <span className="flex items-center justify-center w-8 h-8 rounded-full bg-blue-100 text-blue-700 text-sm font-medium">
                        {index + 1}
                      </span>
                      <div>
                        <h4 className="text-sm font-medium text-gray-900">
                          {step.name || step.step_name}
                        </h4>
                        <div className="mt-2 flex flex-wrap gap-2">
                          <span className="inline-flex items-center px-2 py-1 rounded text-xs font-medium bg-gray-100 text-gray-700">
                            {step.action_type || step.step_type}
                          </span>
                          {(step.requires_approval || step.is_mandatory) && (
                            <span className="inline-flex items-center px-2 py-1 rounded text-xs font-medium bg-yellow-100 text-yellow-800">
                              Requires Approval
                            </span>
                          )}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* Workflow Execution Panel */}
      {workflow.status === 'ACTIVE' && (
        <WorkflowExecutionPanel workflowId={workflow.id} />
      )}
    </div>
  );
}

export default async function WorkflowDetailPage({
  params,
}: {
  params: { id: string };
}) {
  await requireAuth();
  await requireProfile();

  return (
    <AppShell>
      <PageContainer>
        <div className="mb-4">
          <Link href="/workflows" className="text-sm text-blue-600 hover:text-blue-800">
            ← Back to Workflows
          </Link>
        </div>

        <Suspense fallback={<LoadingState />}>
          <WorkflowDetailContent workflowId={params.id} />
        </Suspense>
      </PageContainer>
    </AppShell>
  );
}

function StatusBadge({ status }: { status: string }) {
  const styles = {
    DRAFT: 'bg-gray-100 text-gray-800',
    VALIDATING: 'bg-yellow-100 text-yellow-800',
    READY: 'bg-green-100 text-green-800',
    ACTIVE: 'bg-blue-100 text-blue-800',
    INACTIVE: 'bg-gray-100 text-gray-600',
    ARCHIVED: 'bg-gray-100 text-gray-500',
  };

  return (
    <span
      className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${
        styles[status as keyof typeof styles] || styles.DRAFT
      }`}
    >
      {status}
    </span>
  );
}
